
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/majestic
      database: majestic_cup
      authentication-database: admin

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG